version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=camilaShoppingDB
      - POSTGRES_USER=cesardev31
      - POSTGRES_PASSWORD=dragones123
    ports:
      - "5431:5431"

volumes:
  postgres_data:
