version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    environment:
      - POSTGRES_DB=xxxxxxxx
      - POSTGRES_USER=xxxxxxx
      - POSTGRES_PASSWORD=xxxxxxxxx
    ports:
      - "5431:5431"

  server:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
